spring.application.name=stt-backend

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/stt_app?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

assemblyai.api.key=a84e17236fe84d62be11e5f763a42db5