spring.application.name=stt-backend

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

assemblyai.api.key=${ASSEMBLYAI_API_KEY}

spring.datasource.hikari.data-source-properties.sslmode=verify-full
spring.datasource.hikari.data-source-properties.sslrootcert=ca.pem
